Legacy SDK compliance continue (#2045)
* Migrate from log4j:log4j:1.2.17 to log4j-core:2.15.0

* Upgrade log4j-classic

* Upgrade gson

* Upgrade xstream

* Make log4j:1.2.17 compileOnly

* Revert tests

* Use testImplementation instead of compile

* Keep compileOnly

* Fix mxparser classNoFound

* Use testCompile

* Revert xstream update for now

* Try 1.4.28 xstream

* Revert xstream NoClassDefFoundError

* Revert gson for now since it doesn't support java 7